/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalaryComparisonRouteImport } from './routes/salary-comparison'
import { Route as MaxHiringFeeRouteImport } from './routes/max-hiring-fee'
import { Route as IndexRouteImport } from './routes/index'

const SalaryComparisonRoute = SalaryComparisonRouteImport.update({
  id: '/salary-comparison',
  path: '/salary-comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const MaxHiringFeeRoute = MaxHiringFeeRouteImport.update({
  id: '/max-hiring-fee',
  path: '/max-hiring-fee',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/max-hiring-fee': typeof MaxHiringFeeRoute
  '/salary-comparison': typeof SalaryComparisonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/max-hiring-fee': typeof MaxHiringFeeRoute
  '/salary-comparison': typeof SalaryComparisonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/max-hiring-fee': typeof MaxHiringFeeRoute
  '/salary-comparison': typeof SalaryComparisonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/max-hiring-fee' | '/salary-comparison'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/max-hiring-fee' | '/salary-comparison'
  id: '__root__' | '/' | '/max-hiring-fee' | '/salary-comparison'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MaxHiringFeeRoute: typeof MaxHiringFeeRoute
  SalaryComparisonRoute: typeof SalaryComparisonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/salary-comparison': {
      id: '/salary-comparison'
      path: '/salary-comparison'
      fullPath: '/salary-comparison'
      preLoaderRoute: typeof SalaryComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/max-hiring-fee': {
      id: '/max-hiring-fee'
      path: '/max-hiring-fee'
      fullPath: '/max-hiring-fee'
      preLoaderRoute: typeof MaxHiringFeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MaxHiringFeeRoute: MaxHiringFeeRoute,
  SalaryComparisonRoute: SalaryComparisonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
